title: James F. D. Henderson
description: PhD Student | Immunology | Biophysics

email: james.henderson.19@ucl.ac.uk
github_url: https://github.com/jhenderson0
scholar_url: https://scholar.google.com/citations?user=6r6_TgkAAAAJ&hl=en&oi=ao

profile_image: 

markdown: kramdown